# downloads data

all: data/birthnames.csv data/birthnames_top_100.csv

data/birthnames.csv: src/save_babynames_data.py
	python src/save_babynames_data.py

data/birthnames_top_100.csv: src/save_babynames_data.py
	python src/save_babynames_data.py
